config/routes.rb
Rails.application.routes.draw do
  root "users#show"

  resources :users, only: [:show, :index, :destroy] do
    resources :monologues, only: [:new, :create, :destroy, :edit, :update] do
      member do
        post 'copy_monologue'
      end
    end
  end

  resources :monologues, only: [:index, :show]

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monologue.rb
class Monologue < ApplicationRecord
  belongs_to :user
  has_many :memories

  validates :play_title, presence: true
  validates :text_file, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :profile_photo, ProfilePhotoUploader
  has_many :monologues

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :role, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    role == "admin"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :profile_photo])

    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :profile_photo])
  end
end

app/controllers/monologues_controller.rb
class MonologuesController < ApplicationController
  before_action :authorize_user

  def show
    @user = current_user
    @monologue = Monologue.find(params[:id])
    @response = @monologue.text_file

    respond_to do |format|
      format.json { render json: { monologue: @monologue, response: @response } }
      format.html
    end
  end

  def new
    @user = current_user
    @monologue = Monologue.new
  end

  def create
    @user = current_user
    upload = params[:monologue][:text_file].tempfile.read
    @monologue = Monologue.new(monologue_params)
    @monologue.user_id = @user.id
    @monologue.text_file = upload

    if @monologue.save
      flash[:notice] = "You uploaded a new monologue! Congratulations!"
      redirect_to monologue_path(@monologue.id)
    else
      flash[:notice] = @monologue.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
    @user = current_user
    @monologue = Monologue.find(params[:id])
  end

  def update
    @monologue = Monologue.find(params[:id])

    if @monologue.update_attributes(monologue_params)
      flash[:notice] = "Monologue was successfully edited!"
      redirect_to root_path
    else
      flash[:notice] = @monologue.errors.full_messages.join(", ")
      render :edited
    end
  end

  def destroy
    Monologue.find(params[:id]).destroy
    flash[:notice] = "Monologue was deleted"
    redirect_to root_path
  end

  def copy_monologue
    @copied = Monologue.find(params[:id])
    @user = current_user

    @monologue = Monologue.new(play_title: "#{@copied.play_title}", character: "#{@copied.character}", page_number: "#{@copied.page_number}", text_file: "#{@copied.text_file}", genre: "#{@copied.genre}", user_id: @user.id)

    if @monologue.save
      flash[:notice] = "You have successfully copied a monologue"
      redirect_to user_path(current_user)
    else
      flash[:notice] = @monologue.errors.full_messages.join(', ')
      redirect_to users_path
    end
  end

  private

  def monologue_params
    params.require(:monologue).permit(:play_title, :character, :page_number, :text_file, :genre, :author, :created_at, :updated_at)
  end

  protected

  def authorize_user
    if !user_signed_in?
      redirect_to new_user_session_path
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authorize_user

  def show
    @user = current_user
  end

  protected

  def authorize_user
    if !user_signed_in?
      redirect_to new_user_session_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_user

  def show
    if params[:id].nil?
      @user = current_user
    else
      @user = User.find(params[:id])
    end 
  end

  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "User was deleted!"
    redirect_to users_path
  end

  protected

  def authorize_user
    if !user_signed_in?
      redirect_to new_user_session_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Monomemorizer</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css?family=Gudea" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css?family=Chonburi" rel="stylesheet">
     <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
    <ul id="nav-bar-dropdown" class="dropdown-content">
      <% if user_signed_in? %>
      <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "menu-links" %></li>
      <li><%= link_to 'Profile', user_path(current_user), class: "menu-links" %></li>
      <li><%= link_to 'All Users', users_path, class: "menu-links" %></li>
      <% else %>
      <li> <%= link_to 'Sign In', new_user_session_path, class: "menu-links" %> </li>
      <li><%= link_to 'Sign Up', new_user_registration_path, class: "menu-links" %></li>
      <% end %>
    </ul>
    <nav>
      <div class="nav-wrapper #ef6c00 orange darken-3">
        <a class="nav-title">Monomemorizer</a>
        <ul class="right hide-on-med-and-down">
          <% if user_signed_in? %>
            <li class="profile-photo"><%= image_tag(current_user.profile_photo.small_profile_picture) %></li>
          <% end %>
          <li><a class="dropdown-button menu-button" href="#" data-activates="nav-bar-dropdown">Menu<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
      </div>
      <p class="notice center-align"> <%= notice %></p>
      <p class="alert center-align"> <%= alert %></p>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/monologues/edit.html.erb
<div class="new-monologue-image center-align">
  <div class="container center-align monologue-form">
    <h1 class="monologue-header">Edit Monologue</h1>
    <%= form_for [@user, @monologue] do |f| %>
      <div class="left-align">
        <%= f.label :play_title, "Title Of Play", class: "form-labels" %>
        <%= f.text_field :play_title, value: @monologue.play_title, class: "form-fields" %>
      </div>

      <div class="left-align">
        <%= f.label :author, "Author", class: "form-labels" %>
        <%= f.text_field :author, value: @monologue.author, class: "form-fields" %>
      </div>

      <div class="left-align">
        <%= f.label :character, class: "form-labels" %>
        <%= f.text_field :character, value: @monologue.character, class: "form-fields" %>
      </div>

      <div class="left-align">
        <%= f.label :page_number, "Page Number", class: "form-labels" %>
        <%= f.text_field :page_number, value: @monologue.page_number, class: "form-fields" %>
      </div>

      <div class="left-align">
        <%= f.label :genre, class: "form-labels" %>
        <%= f.text_field :genre, value: @monologue.genre, class: "form-fields" %>
      </div>

      <div class="left-align">
        <%= f.label :text_file, "Monologue Text", class: "form-labels" %>
        <%= f.text_area :text_file, value: @monologue.text_file, class: "form-fields" %>
      </div>

      <button class="btn waves-effect waves-teal #ef6c00 orange darken-3">
        <i class="material-icons right"></i>
        <%= f.submit "Update Your Monologue" %>
      </button>
    <% end %>
  </div>
</div>

app/views/monologues/new.html.erb
<div class="new-monologue-image center-align">
  <div class="container center-align monologue-form">
    <h1 class="monologue-header">New Monologue</h1>
    <%= form_for [@user, @monologue] do |f| %>
      <div class="left-align">
        <%= f.label :play_title, "Title Of Play", class: "form-labels" %>
        <%= f.text_field :play_title %>
      </div>

      <div class="left-align">
        <%= f.label :author, "Author", class: "form-labels" %>
        <%= f.text_field :author %>
      </div>

      <div class="left-align">
        <%= f.label :character, class: "form-labels" %>
        <%= f.text_field :character %>
      </div>

      <div class="left-align">
        <%= f.label :page_number, "Page Number", class: "form-labels" %>
        <%= f.text_field :page_number %>
      </div>

      <div class="left-align">
        <%= f.label :genre, class: "form-labels" %>
        <%= f.text_field :genre %>
      </div>

      <div class="text-upload">
        <p class="white-title center-align form-labels">Upload Your Monologue! (only txt files)</p>
        <%= f.file_field :text_file, accept: "text" %>
      </div>

      <button class="btn waves-effect waves-teal #ef6c00 orange darken-3">
        <i class="material-icons right"></i>
        <%= f.submit "Add A Monologue" %>
      </button>
    <% end %>
  </div>
</div>

app/views/monologues/show.html.erb
<div class="react monologue-image" id="react"></div>

app/views/users/index.html.erb
<div class="profile-image center-align">
  <div class="container center-align user-container">
    <h1 class="user-header">All Users</h1>
      <% @users.each do |user| %>
        <hr>
        <div class="hoverable">
          <h4 class="individual-user"> <%= link_to "#{user.first_name} #{user.last_name}'s Profile", user_path(user), class: "user-link" %></h4>
          <% if current_user.try(:admin?) %>
            <%= button_to "Delete User", user_path(user), data: { confirm: "Are you sure?" }, method: :delete, id: "#{user.id}", class: "delete-user btn waves-effect waves-teal #c62828 red darken-3" %>
          <% end %>
        </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile-image center-align">
  <div class="container center-align profile-container">
    <h1 class="profile-header"> <%= @user.first_name %>'s Profile </h1>
      <% @user.monologues.sort_by(&:created_at).each do |monologue| %>
      <hr>
      <div class="hoverable">
        <h4 class="individual-monologue"><%= link_to "#{monologue.play_title}", monologue_path(monologue.id), class: "monologue-link" %></h4>
        <span class="character"><%= monologue.character %></span>
        <span class="page">Page Number: <%= monologue.page_number %></span>
      <% if monologue.user == current_user || current_user.try(:admin?) %>
        <%= button_to "Delete Monologue", user_monologue_path(current_user, monologue.id), data: { confirm: "Are you sure?" }, method: :delete, class: "delete-monologue btn waves-effect waves-teal #c62828 red darken-3" %>
      <% end %>
      <% if current_user != @user %>
        <%= button_to "Copy To Your Profile", copy_monologue_user_monologue_path(@user.id, monologue.id), class: "btn waves-effect waves-teal #ef6c00 orange darken-3" %>
      <% else %>
        <%= button_to "Edit Monologue", edit_user_monologue_path(current_user, monologue.id), method: :get, class: "edit-monologue btn waves-effect waves-teal #ef6c00 orange darken-3" %>
      <% end %>
    </div>
    <% end %>
  </div>
  <% if current_user == @user %>
    <div class="container center-align add-monologue-link-container">
      <%= button_to 'Add A New Monologue', new_user_monologue_path(current_user), method: :get, class: "profile-button btn waves-effect waves-teal #00b0ff light-blue accent-3" %>
      <%= button_to 'Edit Profile', edit_user_registration_path(current_user), method: :get, class: "profile-button btn waves-effect waves-teal #ef6c00 orange darken-3" %>
    </div>
  <% end %>
</div>